server:
  port: 8081
  servlet:
    session:
      timeout: 0
          
spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  resources:
    static-locations: classpath:/static/
    
  mail:
    host: smtp.qq.com
    port: 587
    protocol: smtp
    username: 916106209@qq.com
    password: cahkttifpeixbbdj
    default-encoding: UTF-8
    
  http:
    encoding:
      enabled: true
      force: true
      charset: UTF-8
      
  session:
    store-type: redis
    
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 
    timeout: 0
    jedis:
      pool:
        max-active: 20
        max-idle: 20
        min-idle: 0
        max-wait: -1
    
datasource:
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/tmall_ssm?unicode=true&characterEncoding=utf8&useSSL=false
  username: root
  password: admin
  initialSize: 1
  minIdle: 1
  maxActive: 20
  maxWait: 60000
  minEvictableIdleTimeMillis: 300000
  timeBetweenEvictionRunsMillis: 60000
  defaultAutoCommit: false
  poolPreparedStatements: true
  maxPoolPreparedStatementPerConnectionSize: 20
  
mybatis-config-file: mybatis-config.xml
mapper-path: /mapper/**.xml
pojo-package: com.zhihao.tmall.pojo

mail:
  subject: 注册账户激活
  username: username
  code: code